spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33306/coupon_example
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 36379