version: '3'

name: coupon-system

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: coupon_example
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 33306:3306
  redis:
    image: redis:6
    restart: always
    ports:
      - 36379:6379
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock